from odoo import _, api, fields, models
from odoo.exceptions import ValidationError, UserError

# class BackOfficeSettings(models.TransientModel):
#     _inherit = 'res.config.settings'

#     sales_account = fields.Many2one('account.account', string='Sales Account', config_parameter="backoffice.sales_account")
#     bank_account  = fields.Many2one('account.account', string='Bank Account', config_parameter="backoffice.bank_account")
#     ar_account = fields.Many2one('account.account', string='AR Account', config_parameter="backoffice.ar_account")

#Commit
#123